# frozen_string_literal: true

require 'open3'

class ComplianceFileCheckQueueService
  MAX_UPLOAD_SIZE = 50.gigabytes
  ALLOWED_EXTENSIONS = %w[.loom .h5ad].freeze
  UNSUPPORTED_FORMAT_ERROR_CODE = 'unsupported_file_format'
  ASAP_RUN_CONTAINER = ENV.fetch('ASAP_RUN_CONTAINER').freeze
  REPO_ROOT = ENV.fetch('SCFAIR_EXTRACT_REPO_ROOT', '/data/asap2_test').freeze

  FORMAT_DETECT_PY = <<~'PYTHON'
    import h5py
    import sys

    path = sys.argv[1]
    with h5py.File(path, "r") as f:
        keys = set(f.keys())
        if "matrix" in keys and ("col_attrs" in keys or "row_attrs" in keys):
            print("loom")
        elif "X" in keys and "obs" in keys and "var" in keys:
            print("h5ad")
        else:
            print("unknown")
  PYTHON

  class UnsupportedFormatError < ArgumentError; end

  class << self
    def allowed_extension?(filename)
      ext = File.extname(filename.to_s).downcase
      ALLOWED_EXTENSIONS.include?(ext)
    end

    def unsupported_format_error_message
      'This tool supports only Loom (.loom) and H5AD (.h5ad) file formats. ' \
        'For other file formats supported by ASAP, you can create an ASAP project and then run the compliance tool on the project ' \
        '(Loom file generated by ASAP).'
    end

    def validate_upload!(filename:, file_size:)
      unless allowed_extension?(filename)
        raise UnsupportedFormatError, unsupported_format_error_message
      end
      raise ArgumentError, "Invalid file size (max #{MAX_UPLOAD_SIZE / 1.gigabyte}GB)" if file_size <= 0 || file_size > MAX_UPLOAD_SIZE
    end

    def detect_compliance_format(path)
      return nil unless path.present? && File.exist?(path)
      return nil unless Basic.hdf5_superblock_file?(path)

      container_path = resolve_container_path(path)
      cmd = ['docker', 'exec', '-i', ASAP_RUN_CONTAINER, 'python3', '-', container_path]
      stdout, _stderr, status = Open3.capture3(*cmd, stdin_data: FORMAT_DETECT_PY)
      return nil unless status.success?

      detected = stdout.to_s.strip
      detected if %w[loom h5ad].include?(detected)
    end

    def validate_downloaded_file!(path)
      detected = detect_compliance_format(path)
      return detected if detected

      FileUtils.rm_f(path)
      raise UnsupportedFormatError, unsupported_format_error_message
    end

    def call(fu:, schema_id: 'scfair_7_1_0')
      new(fu: fu, schema_id: schema_id).call
    end

    def resolve_container_path(path)
      abs = File.expand_path(path)
      return abs if abs.start_with?(REPO_ROOT)

      if abs.start_with?('/srv/asap2_test/')
        return abs.sub('/srv/asap2_test', REPO_ROOT)
      end

      abs
    end
    private :resolve_container_path
  end

  def initialize(fu:, schema_id:)
    @fu = fu
    @schema_id = schema_id.to_s.presence || 'scfair_7_1_0'
  end

  def call
    path = @fu.file_path&.to_s
    raise ArgumentError, 'Upload file not found' if path.blank? || !File.exist?(path)

    self.class.validate_upload!(filename: @fu.name.presence || path, file_size: File.size(path))

    task_id = SecureRandom.uuid
    original_filename = @fu.name.presence || File.basename(path)
    initial = {
      status: 'queued',
      task_id: task_id,
      progress: 45,
      message: 'Validation queued'
    }
    IsolatedComplianceStatusStore.write(task_id, initial)
    @fu.update!(status: 'validating')
    IsolatedComplianceValidationJob.perform_later(
      task_id,
      path,
      @schema_id,
      original_filename,
      fu_id: @fu.id
    )

    {
      task_id: task_id,
      status: 'queued',
      filename: original_filename,
      schema_id: @schema_id
    }
  end
end
